### ISSUE TITLE
[Question] What APIs would I use to change a player's skin to a file

### ISSUE THREAD

**Issue by 28andrew** [InventivetalentDev/MineskinClient#1]
What APIs would I use to change a player's skin to a file. I'm guessing this one and NickNamer?

**Comment by InventivetalentDev** [comment]
Yes.
You can use [#loadCustomSkin](http://ci.inventivetalent.org/job/NickNamer/javadoc/org/inventivetalent/nicknamer/api/PluginNickManager.html#loadCustomSkin-java.lang.String-org.inventivetalent.mcwrapper.auth.GameProfileWrapper-) to inject the texture value & signature and [#setCustomSkin](http://ci.inventivetalent.org/job/NickNamer/javadoc/org/inventivetalent/nicknamer/api/PluginNickManager.html#setCustomSkin-java.util.UUID-java.lang.String-) to apply it to a player.

**Comment by 28andrew** [comment]
Thanks so much.
