### ISSUE TITLE
Downgrade to java 17

### ISSUE THREAD

**Issue by Suiranoil** [InventivetalentDev/MineskinClient#21]
**Is your feature request related to a problem? Please describe.**
I want to use MineskinClient in my mod https://github.com/Suiranoil/SkinRestorer and i want to support minecraft versions 1.20.x-1.21.x. But minecraft <=1.20.4 is built using java 17 making it impossible to port my mod to these versions. 

**Describe the solution you'd like**
Downgrade java version to at least 17.

**Describe alternatives you've considered**
Using old version.

**Additional context**
None

**Comment by crqch** [comment]
Hi, did you find a solution?

**Comment by Suiranoil** [comment]
I decided to make my own fork https://github.com/Suiranoil/MineskinClient where i downgraded java to 17 and made dependencies `provided` so that they are not included in mod's jar when using jarInJar
It is available here https://reposilite.lionarius.ru/#/releases/org/mineskin
