### ISSUE TITLE
mineskin API doesnt work often

### ISSUE THREAD

**Issue by Xayanix** [InventivetalentDev/MineskinClient#4]
Hi,

im getting often errors like this: { "error": "Failed to log into the account (#20). Please try again later", "details": "Login Failed. (403, jona): {\"error\":\"ForbiddenOperationException\",\"errorMessage\":\"Invalid credentials. Invalid username or password.\"}" }

(using api.mineskin.org)

**Comment by InventivetalentDev** [comment]
Please refer to https://help.mojang.com/customer/en/portal/articles/781529-login-failed
Nothing I can do about that, sorry. Minecraft account logins fail sometimes for no apparent reason, and start working again after some time.

**Comment by Xayanix** [comment]
How long it'll take to bring API to work again? :(

**Comment by yannicklamprecht** [comment]
As @InventivetalentDev stated that is **not** an issues with her MineskinAPI. Mojang has this issues.
