### ISSUE TITLE
Hey,

### ISSUE THREAD

**Issue by rplcnn** [InventivetalentDev/MineskinClient#5]
How I can check "RepublicanSensei"'s data with this API.

**Comment by InventivetalentDev** [comment]
what?

**Comment by rplcnn** [comment]
I want to get player's skull with custom nbt (base64 code) 
How can i use that api. I would like to see how it works with playerName.

For example: mineskinAPI.getCode(player)

**Comment by InventivetalentDev** [comment]
#generateUser

**Comment by rplcnn** [comment]
How can i use this api. I can't turn this source to .jar so i can't use this in build paths

**Comment by rplcnn** [comment]
MineskinClient mineskinClient = new MineskinClient();
		mineskinClient.generateUser(player.getUniqueId(), SkinOptions.create(player.getName(), Model.SLIM, Visibility.PUBLIC), new SkinCallback()) {
			

!Cannot instantiate the type SkinCallback

How can i get the skull(ItemStack)

**Comment by InventivetalentDev** [comment]
Learn Java, please. You need an abstract interface class as the callback.
